<a href="https://colab.research.google.com/github/JaiKumar1717/FMML-Notebook/blob/main/Lab_1_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as matplt

Matrix Transpose

In [ ]:
# transpose of matrix as nested list
a = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 0]]
b = np.transpose(a)
print('a\n',a)
print('b\n',b)

a
 [[1, 2, 3, 4, 5], [6, 7, 8, 9, 0]]
b
 [[1 6]
 [2 7]
 [3 8]
 [4 9]
 [5 0]]


If the matrix is a NumPy array, it can be treated as an object and method T can be applied over it as follows.

In [ ]:
#transpose of matrix (as Numpy array)
print("Matrix and its Transpose")
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 0]])
b = a.T
print('a\n',a)
print('b\n',b)

Matrix and its Transpose
a
 [[1 2 3 4 5]
 [6 7 8 9 0]]
b
 [[1 6]
 [2 7]
 [3 8]
 [4 9]
 [5 0]]



The dot method of NumPy performs dot-matrix product (scalar product) for 1D or higher dimensional arrays. If the inputs are scalars (numbers), it performs multiplication.

In [ ]:
#Scalars
a = 5
b = 4
z = np.dot(a,b)
print(z)

20


In [ ]:
z = a*b
print(z)

20


In the case of one- or higher-dimensional arrays, the inputs can be either NumPy arrays, Python arrays, Python lists or Python’s nested lists.

In [ ]:
# 1D array or vectors
a = np.array([4,6,3])
b = np.array([5,7,9])
z = np.dot(a,b)
print(z)

89


In [ ]:
#2D arrays or matrices
a = [[3,5,4],[6,-7,8],[7,4,3]]
b = [[4,6,2],[3,-5,7],[8,0,1]]
z = np.dot(a,b)
print(z)

[[ 59  -7  45]
 [ 67  71 -29]
 [ 64  22  45]]


We can obtained the same result using np.matmul().

In [ ]:
z = np.matmul(a,b)
print(z)

[[ 59  -7  45]
 [ 67  71 -29]
 [ 64  22  45]]


> Numpy Arrays

A NumPy array is a Numpy object upon which the dot method can be performed as below. However, this method accepts only NumPy arrays to operate on.

In [ ]:
# convert lists into Numpy arrays
newa = np.array(a)
newb = np.array(b)
z = newa.dot(newb)
print(z)

[[ 59  -7  45]
 [ 67  71 -29]
 [ 64  22  45]]



>The multi_dot method

It performs dot (scalar) product with 2 or more input matrices. First and last arrays can be either 1D or 2D arrays. However, the dimensions of the matrices must suit subsequent scalar matrix multiplication.

In [ ]:
 # matrices with random integers: entries ranging from -4 to 4
 a = np.random.randint(-4,4,(500,5))
 b = np.random.randint(-4,4,(5,1000))
 c = np.random.randint(-4,4,(1000,10))
 d = np.random.randint(-4,4,(10,2000))
 e = np.random.randint(-4,4,(2000,200))

 # perform multiple matrix multiplication
 z = np.linalg.multi_dot([a,b,c,d,e])